#!/usr/bin/env node
// codystem-10x T16 — token instrumentation (honest proxy).
//
// The harness has no in-repo AGENT runtime to instrument, so per-session token accounting needs
// runtime telemetry from the agent host — out of this repo's scope, and we do NOT fabricate a
// number for it. What IS measurable in-repo is the TOOL's output size: the tokens a consuming
// agent pays to read a status response. This measures the full vs compact (compactSummary) forms
// — the reduction features 005/008 delivered — as a real, honest token proxy.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { statusForFiles } from "../dist/status.js";
import { compactSummary } from "../dist/query.js";
import { findLedgers } from "../dist/discover.js";

const ledgers = await findLedgers();
const full = await statusForFiles(ledgers);
const compact = compactSummary(full);

const est = (o) => {
  const s = JSON.stringify(o);
  return { bytes: Buffer.byteLength(s), tokens: Math.ceil(s.length / 4) };
};
const f = est(full);
const c = est(compact);
const pct = f.tokens === 0 ? 0 : Math.round((1 - c.tokens / f.tokens) * 100);

const report = `# CODYSTEM token instrumentation (codystem-10x T16)

Tokens a consuming agent pays to read a status response — full vs compact (\`compactSummary\`).
Token estimate = chars / 4 (rough).

| form | JSON bytes | ~tokens |
|------|-----------:|--------:|
| full (per-task) | ${f.bytes} | ${f.tokens} |
| compact (per-feature counts) | ${c.bytes} | ${c.tokens} |

**Compact is ~${pct}% fewer tokens** for the same ${full.features.length}-feature overview.

## Honest limitation
This is the TOOL's OUTPUT token proxy — real for a consuming agent. It is NOT per-agent-session
token accounting (context + reasoning + tool I/O across a whole task), which is what the
BLUEPRINT's "small, high-signal context / fewer tokens" claim is really about. That needs runtime
telemetry from the agent host (e.g. Claude Code usage), which this repo cannot produce — so it is
stated, not invented. What is measured here is real; what isn't measurable in-repo is labelled so.

_Generated by bench/tokens.mjs — \`node bench/tokens.mjs\`._
`;

writeFileSync(join(process.cwd(), "bench", "token-report.md"), report);
console.log(`tokens: full ~${f.tokens}, compact ~${c.tokens} (${pct}% fewer for the overview)`);
