// codystem-to-10of10 F3: ops over a gate-run event series (bench/ops/gate-events.jsonl). Pure
// functions — no I/O, no clock — so they are exhaustively testable. Each event is one gate run
// {ts, gate, outcome, sig}. This turns the series into: a DEDUPED alert stream (alert on the
// transition INTO failure, stay quiet while it keeps failing, re-alert after a recovery) and a
// rolling gate-failure-rate report.

export interface GateEvent {
  ts: string; // ISO timestamp of the run
  gate: string; // which gate (verify | stress | redteam | …)
  outcome: "pass" | "fail";
  sig?: string; // failure signature (defaults to the gate name) — the dedup/grouping key
}

const REQUIRED: (keyof GateEvent)[] = ["ts", "gate", "outcome"];

export function parseEvents(text: string): GateEvent[] {
  const out: GateEvent[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const o = JSON.parse(line);
    for (const k of REQUIRED)
      if (!(k in o)) throw new Error(`gate event missing '${String(k)}': ${line}`);
    if (o.outcome !== "pass" && o.outcome !== "fail")
      throw new Error(`gate event has invalid outcome: ${line}`);
    out.push(o as GateEvent);
  }
  return out;
}

// Grouping/dedup key is namespaced by gate, so two DIFFERENT gates that happen to use the same
// `sig` string do not collide into one signature (the PR #23 finding). Readable form: "gate/sig".
const key = (e: GateEvent): string => (e.sig ? `${e.gate}/${e.sig}` : e.gate);

/**
 * Deduped alerts: a failure alerts only on the TRANSITION into failure for its signature. Repeated
 * identical failures stay quiet (no alert storm); a pass clears the signature so the next failure
 * re-alerts. Returns the fail events that warrant an alert, in order.
 */
export function dedupedAlerts(events: GateEvent[]): GateEvent[] {
  const alerting = new Set<string>();
  const out: GateEvent[] = [];
  for (const e of events) {
    const k = key(e);
    if (e.outcome === "fail") {
      if (!alerting.has(k)) {
        out.push(e);
        alerting.add(k);
      }
    } else {
      alerting.delete(k);
    }
  }
  return out;
}

/** Failure rate over the whole series, or the last `lastN` runs (lastN=0 → an empty window → 0). */
export function failureRate(events: GateEvent[], lastN?: number): number {
  const slice = lastN === undefined ? events : lastN <= 0 ? [] : events.slice(-lastN);
  if (!slice.length) return 0;
  const fails = slice.filter((e) => e.outcome === "fail").length;
  return Math.round((fails / slice.length) * 1000) / 1000;
}

/** The most frequent failure signatures. */
export function topFailures(events: GateEvent[], n = 5): { sig: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const e of events)
    if (e.outcome === "fail") counts.set(key(e), (counts.get(key(e)) ?? 0) + 1);
  return [...counts]
    .map(([sig, count]) => ({ sig, count }))
    .sort((a, b) => b.count - a.count || a.sig.localeCompare(b.sig))
    .slice(0, n);
}

/** Signatures currently in a failing (unrecovered) state at the end of the series. */
export function openFailures(events: GateEvent[]): string[] {
  const state = new Map<string, "pass" | "fail">();
  for (const e of events) state.set(key(e), e.outcome);
  return [...state.entries()]
    .filter(([, v]) => v === "fail")
    .map(([k]) => k)
    .sort();
}

export interface OpsSummary {
  runs: number;
  failures: number;
  failureRatePct: number;
  rollingRatePct: number; // over the last `window` runs
  alerts: number; // deduped
  openFailures: string[];
  top: { sig: string; count: number }[];
}

export function summarize(events: GateEvent[], window = 20): OpsSummary {
  return {
    runs: events.length,
    failures: events.filter((e) => e.outcome === "fail").length,
    failureRatePct: Math.round(failureRate(events) * 1000) / 10,
    rollingRatePct: Math.round(failureRate(events, window) * 1000) / 10,
    alerts: dedupedAlerts(events).length,
    openFailures: openFailures(events),
    top: topFailures(events),
  };
}

export function renderOpsReport(events: GateEvent[], window = 20): string {
  const s = summarize(events, window);
  const topRows = s.top.length
    ? s.top.map((t) => `| ${t.sig} | ${t.count} |`).join("\n")
    : "| _none_ | 0 |";
  return `# Gate ops report (codystem-to-10of10 F3)

Rolling view of gate-run outcomes from \`bench/ops/gate-events.jsonl\`. Alerts are DEDUPED — one alert
per failure onset, re-alerting only after a recovery.

| metric | value |
|---|---|
| runs | ${s.runs} |
| failures | ${s.failures} |
| failure rate | ${s.failureRatePct}% |
| rolling rate (last ${window}) | ${s.rollingRatePct}% |
| deduped alerts | ${s.alerts} |
| currently failing | ${s.openFailures.length ? s.openFailures.join(", ") : "none"} |

## Top failure signatures
| signature | failures |
|---|---|
${topRows}

_Generated by src/ops.ts. Regenerate with \`pnpm run ops:report\`._
`;
}
