// codystem-to-10of10 C2: scoring for the seeded-bug review harness. Pure functions over a corpus of
// labelled cases (each KNOWN buggy or clean) + a reviewer's blind verdicts. Produces the catch-rate
// (seeded bugs the reviewer flagged) and false-positive rate (clean controls it wrongly flagged) —
// the empirical numbers behind "the independent review actually catches bugs". No I/O, so the
// scoring is exhaustively testable independent of any live reviewer run.

export interface ReviewCase {
  id: string;
  bugClass: string; // e.g. off-by-one, null-deref, wrong-operator, resource-leak
  buggy: boolean; // ground truth
}

export interface ReviewVerdict {
  id: string;
  flaggedBuggy: boolean; // what the (blind) reviewer decided
}

export interface Score {
  seeded: number; // # ground-truth buggy cases
  clean: number; // # ground-truth clean cases
  scored: number; // # cases that got a verdict
  unscored: string[]; // case ids with no verdict (treated as NOT caught / NOT fp)
  caught: number; // seeded flagged buggy (true positives)
  missed: number; // seeded flagged clean or unscored (false negatives)
  falsePositives: number; // clean flagged buggy
  catchRatePct: number; // caught / seeded  (100 desired)
  fpRatePct: number; // falsePositives / clean  (<10 desired)
  byClass: Record<string, { seeded: number; caught: number }>;
  pass: boolean;
  reasons: string[];
}

const pct = (num: number, den: number): number =>
  den === 0 ? 0 : Math.round((num / den) * 1000) / 10;

/**
 * Score reviewer verdicts against ground truth. A case with no verdict is counted as NOT caught
 * (a miss) and NOT a false positive — a reviewer that abstains cannot claim the catch. Thresholds:
 * ≥ minSeeded seeded cases, 100% catch, and < maxFpPct% false positives.
 */
export function score(
  cases: ReviewCase[],
  verdicts: ReviewVerdict[],
  opts: { minSeeded?: number; maxFpPct?: number } = {}
): Score {
  const minSeeded = opts.minSeeded ?? 20;
  const maxFpPct = opts.maxFpPct ?? 10;
  const verdictById = new Map(verdicts.map((v) => [v.id, v]));

  const seededCases = cases.filter((c) => c.buggy);
  const cleanCases = cases.filter((c) => !c.buggy);
  const unscored: string[] = [];
  let caught = 0;
  let falsePositives = 0;
  const byClass: Record<string, { seeded: number; caught: number }> = {};

  for (const c of cases) {
    const v = verdictById.get(c.id);
    if (!v) unscored.push(c.id);
    if (c.buggy) {
      const bc = (byClass[c.bugClass] ??= { seeded: 0, caught: 0 });
      bc.seeded++;
      if (v?.flaggedBuggy) {
        caught++;
        bc.caught++;
      }
    } else if (v?.flaggedBuggy) {
      falsePositives++;
    }
  }

  const seeded = seededCases.length;
  const clean = cleanCases.length;
  const catchRatePct = pct(caught, seeded);
  const fpRatePct = pct(falsePositives, clean);

  const reasons: string[] = [];
  if (seeded < minSeeded)
    reasons.push(`only ${seeded}/${minSeeded} seeded bugs (corpus too small)`);
  if (catchRatePct < 100)
    reasons.push(`catch rate ${catchRatePct}% < 100% (${seeded - caught} missed)`);
  if (fpRatePct >= maxFpPct) reasons.push(`false-positive rate ${fpRatePct}% ≥ ${maxFpPct}%`);
  const pass = seeded >= minSeeded && catchRatePct === 100 && fpRatePct < maxFpPct;
  if (pass)
    reasons.push(
      `${seeded} seeded caught ${caught}/${seeded}, ${falsePositives}/${clean} FP (${fpRatePct}%)`
    );

  return {
    seeded,
    clean,
    scored: cases.length - unscored.length,
    unscored,
    caught,
    missed: seeded - caught,
    falsePositives,
    catchRatePct,
    fpRatePct,
    byClass,
    pass,
    reasons,
  };
}

/** Render a markdown report of the score. */
export function renderReport(s: Score): string {
  const classRows = Object.entries(s.byClass)
    .sort()
    .map(([k, v]) => `| ${k} | ${v.caught}/${v.seeded} |`)
    .join("\n");
  return `# Seeded-bug review harness (codystem-to-10of10 C2)

Measures whether the independent (different-model) reviewer catches KNOWN planted bugs, and how often
it false-flags clean controls. Corpus is blind to the reviewer (labels withheld); this scores its
verdicts against ground truth.

**Verdict:** ${s.pass ? "✅ PASS" : "⏳/❌"} — ${s.reasons.join("; ")}

| metric | value |
|---|---|
| seeded bugs | ${s.seeded} |
| clean controls | ${s.clean} |
| caught (true positives) | ${s.caught}/${s.seeded} |
| missed (false negatives) | ${s.missed} |
| false positives | ${s.falsePositives}/${s.clean} |
| catch rate | ${s.catchRatePct}% |
| false-positive rate | ${s.fpRatePct}% |
| unscored (no verdict) | ${s.unscored.length} |

## By bug class
| class | caught |
|---|---|
${classRows}

_Generated by src/review-score.ts from a reviewer run over bench/review/corpus.jsonl._
`;
}
